### ISSUE TITLE
How to handle datasets with timestamps for algorithms that involve time constraints?

### ISSUE THREAD

**Issue by dmeoli** [LoLei/spmf-py#3]
I'm trying to run an instance of the [HirateYamana](http://www.philippe-fournier-viger.com/spmf/HirateYamana.php) with time constraints. In which format I should encode the dataset to involve the timestamp value for each subsequence?

e.g.

dataset = [
    # sequence: list of events
    [(1, ['a']), (2, ['a', 'b', 'c']), (3, ['a', 'c']), (4, ['c'])],  # event: (timestamp : [list of item])
    [(1, ['a']), (2, ['c']), (3, ['b', 'c'])], 
    [(1, ['a', 'b']), (2, ['d']), (3, ['c']), (4, ['b']), (5, ['c'])], 
    [(1, ['a']), (2, ['c']), (3, ['b']), (4, ['c'])]
]

**Comment by LoLei** [comment]
The link you posted uses an input file with a format like this:
```
contextSequencesTimeExtended.txt
<0> 1 -1 <1> 1 2 3 -1 <2> 1 3 -1 -2
<0> 1 -1 <1> 1 2 -1 <2> 1 2 3 -1 <3> 1 2 3 -1 -2
<0> 1 2 -1 <1> 1 2 -1 -2
<0> 2 -1 <1> 1 2 3 -1 -2
```

You could either (programmatically) reformat and write your data into a file like this as well, or do the same but put it into a raw string as shown in the [examples](https://github.com/LoLei/spmf-py/tree/master/examples). If you're doing the reformatting anyway, maybe you could add this to spmf-py, so that a list like yours could be accepted as direct input for this algorithm as well.
